---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ubuntu/nginx:1.18-22.04_beta
        # volumeMounts:
        # - name: nginx-config-volume
        #   mountPath: /etc/nginx/nginx.conf
        #   subPath: nginx.conf
        # - name: nginx-config-volume
        #   mountPath: /srv/www/index.html
        #   subPath: index.html
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
      # volumes:
      #   - name: nginx-config-volume
      #     configMap:
      #       name: nginx-config
      #       items:
      #       - key: nginx
      #         path: nginx.conf
      #       - key: nginx-site
      #         path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
    name: nginx
