---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-{{ .Values.env }}
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: 31081
    name: nginx
