---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: {{ .Values.env }}
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
    name: nginx
