name: learn-github-actions
on: [push]
env:
  artifact_name: theGame-artifact
jobs:
# build
  build_number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.step1.outputs.BUILD_NUMBER }}
    steps:
      - name: Generate BUILD_NUMBER
        id: step1
          # echo "BUILD_NUMBER=$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')" >> $GITHUB_ENV
        run: |
          echo "::set-output name=BUILD_NUMBER::$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')"
  build-hello-world:
    runs-on: ubuntu-latest
    needs: build_number
    steps:
      - uses: actions/checkout@v2
      - name: Create artifact
        run: echo "It's all in the game" > thegame.txt 
      - name: Validate Artifact name
        run: echo $artifact_name-
      - name: Validate build number
        run: echo ${{ needs.build_number.outputs.build_number }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: $artifact_name-${{ needs.build_number.outputs.build_number }}
          path: thegame.txt
  release-hello-world:
    needs: [build-hello-world, build_number]
    runs-on: ubuntu-latest
    steps:
    # Download all build artifacts and put in proper foders as per standard 
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: $artifact_name-${{ needs.build_number.outputs.build_number }}
    # Pull all git tags/releases
    # Generate new semver compliant version
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate next version
      id: new_version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        # The prefix to use to identify tags
        tag_prefix: ""
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}-prerelease.${increment}+${{ needs.build_number.outputs.build_number }}"
        # change_path: "src/my-service"
        # Named version, will be used as suffix for name version tag
        # namespace: jello-world
        short_tags: false
    - name: Show output version
      run: |
        echo major ${{ steps.new_version.outputs.major }}
        echo minor ${{ steps.new_version.outputs.minor }}
        echo patch ${{ steps.new_version.outputs.patch }}
        echo increment ${{ steps.new_version.outputs.increment }}
        echo version ${{ steps.new_version.outputs.version }}
        echo version_tag ${{ steps.new_version.outputs.version_tag }}
        echo changed ${{ steps.new_version.outputs.changed }}

    # If this is set to true, *every* commit will be treated as a new version.
    # bump_each_commit: false
    # - name: Download semver-tool
    #   run: |
    #     wget -O semver \
    #       https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
    #     chmod +x semver
    #     ./semver --version
    # - name: List git tags
    #   run: git tag -l


# https://github.com/13013SwagR/hello-world/suites/4645262316/artifacts/126000027