name: learn-github-actions
on: [push]
jobs:
  build-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "It's all in the game" > thegame.txt 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: my-build-artifact
          with: thegame.txt


# build
## Create artifact
## Publish artifact