name: learn-github-actions
on: [push]
jobs:
  build-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -alh
      - run: pwd
      - run: tree
# build
## Create artifact
## Publish artifact