name: learn-github-actions
on: [push]
jobs:
# build
  build-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate BUILD_NUMBER
        run: |
          echo "BUILD_NUMBER=$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')" >> $GITHUB_ENV
# echo "DATE=$(date '+%Y%m%dT%H%M%S')" >> $GITHUB_ENV
## Mock Build
      - name: Create artifact
        run: echo "It's all in the game" > thegame.txt 
## Publish artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: theGame-artifact-${{env.BUILD_NUMBER}}
          path: thegame.txt
  release-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: theGame-artifact-${{env.BUILD_NUMBER}}
    - name: Display structure of downloaded files
      run: ls -R
    - uses: ncipollo/release-action@v1
      with:
        tag: 0.0.0


# https://github.com/13013SwagR/hello-world/suites/4645262316/artifacts/126000027