name: learn-github-actions
on: [push]
env:
  artifact_name: theGame-artifact
jobs:
# build
  build-number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.step1.outputs.name }}
    steps:
      - name: Generate BUILD_NUMBER
        id: step1
          # echo "BUILD_NUMBER=$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')" >> $GITHUB_ENV
        run: |
          echo "::set-output name=BUILD_NUMBER::$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')"
  build-hello-world:
    runs-on: ubuntu-latest
    needs: build-number
    steps:
      - uses: actions/checkout@v2
      - name: Create artifact
        run: echo "It's all in the game" > thegame.txt 
      - name: Validate Artifact name
        run: echo $artifact_name-
      - name: Validate build number
        run: echo ${{ needs.build-number.outputs.build_number}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: $artifact_name-${{env.BUILD_NUMBER}}
          path: thegame.txt
  release-hello-world:
    needs: build-hello-world
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: $artifact_name-${{env.BUILD_NUMBER}}
    - name: Display structure of downloaded files
      run: ls -R
    - uses: ncipollo/release-action@v1
      with:
        tag: 0.0.0


# https://github.com/13013SwagR/hello-world/suites/4645262316/artifacts/126000027