name: learn-github-actions
on: [push]
jobs:
  build-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set date
        run: |
          date -I
          echo ${GITHUB_SHA}
          echo "DATE=$(date -I)" >> $GITHUB_ENV
          echo "${{env.DATE}}"
          echo $DATE
          echo "EOF"
      - name: read date
        run: |
          echo "${{env.DATE}}"
          echo $DATE
          echo "EOF"
      - run: echo "It's all in the game" > thegame.txt 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: my-build-artifact-{{ github.sha}}
          path: thegame.txt


# build
## Create artifact
## Publish artifact
# https://github.com/13013SwagR/hello-world/suites/4645262316/artifacts/126000027