name: release-conventional-commit
on: [push]
jobs:
  build_number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.step1.outputs.BUILD_NUMBER }}
    steps:
      - name: Generate BUILD_NUMBER
        id: step1
        run: |
          echo "::set-output name=BUILD_NUMBER::$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')"
##### release ##################################################################################################
  release-test:
    needs: [build_number]
    runs-on: ubuntu-latest
    steps:
    # Pull all git tags/releases
    # Generate new semver compliant version
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate next version
      id: new_version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        # The prefix to use to identify tags
        tag_prefix: ""
        major_pattern: |
          "^((build|ci|docs|feat|fix|perf|refactor|test)(\([a-z 0-9,.\-]+\))?!: [\w \(\),:.;\-#&']+|\nBREAKING CHANGES: [\w \(\),:.;\-#&']+)$"
        minor_pattern: |
          "^(feat)(\([a-z 0-9,.\-]+\))?!?: [\w \(\),:.;\-#&']+$"
        format: "${major}.${minor}.${patch}-prerelease.${increment}+${{ needs.build_number.outputs.build_number }}"
        short_tags: false
    - name: Show output version
      run: |
        echo major ${{ steps.new_version.outputs.major }}
        echo minor ${{ steps.new_version.outputs.minor }}
        echo patch ${{ steps.new_version.outputs.patch }}
        echo increment ${{ steps.new_version.outputs.increment }}
        echo version ${{ steps.new_version.outputs.version }}
        echo version_tag ${{ steps.new_version.outputs.version_tag }}
        echo changed ${{ steps.new_version.outputs.changed }}
 #### publish ############################################
 # Create Github release with assets/artifacts
 # Publishing of artifact could be done separatly 



# https://github.com/13013SwagR/hello-world/suites/4645262316/artifacts/126000027